### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by Stemoulton** [Stemoulton/scary-out-there#1]
Branch name for code..

- Ghouls = 2
- Ghosts  = 10
- Vampires = 5
- Zombies = 9
- Witches = 32
- Trolls = 8

**Comment by githubbabrova** [comment]
Michael D code

* Witches = 12
* Ghosts = 10
* Ghouls = 14
* Trolls = 13
* Zombies = 101
* Vampires = 6

**Comment by chabeezy** [comment]
'ghoul' => 14,
  'ghost' => 10,
  'vampire' => 6,
  'zombie' => 101,
  'witch' => 12,
  'troll' => 13

**Comment by Mr-G-ICT** [comment]
Ghouls:14
Ghosts:10
vampires:6
zombies:101
Witches:12
trolls:10

I know it's wrong but I'm not spending any more time on it....unless i do so tonight.

**Comment by Wolf-PSG** [comment]
Parmjit G

Ghouls: 9
Ghosts: 10
Vampires: 6
Trolls: 11
Zombies: 101
Witches: 12
